// Одежда и её части
export const clothingWords: [string, string][] = [
  ["odeća", "одежда"],
  ["pantalone", "брюки"],
  ["farmerke", "джинсы"],
  ["šorts", "шорты"],
  ["košulja", "рубашка"],
  ["majica", "футболка"],
  ["bluza", "кофта"],
  ["džemper", "свитер"],
  ["jakna", "куртка"],
  ["kaput", "пальто"],
  ["kapuljača", "капюшон"],
  ["haljina", "платье"],
  ["suknja", "юбка"],
  ["donji veš", "нижнее бельё"],
  ["gaće", "трусы"],
  ["čarape", "носки"],
  ["čarape (ženske)", "чулки"],
  ["grudnjak", "бюстгальтер"],
  ["cipele", "туфли"],
  ["patike", "кроссовки"],
  ["sandale", "сандалии"],
  ["čizme", "сапоги"],
  ["štikle", "каблуки"],
  ["kapa", "шапка"],
  ["šešir", "шляпа"],
  ["šal", "шарф"],
  ["rukavice", "перчатки"],
  ["pojas", "ремень"],
  ["kravata", "галстук"],
  ["leptir mašna", "бабочка"],
  ["kaiš", "ремешок"],
  ["džep", "карман"],
  ["dugme", "пуговица"],
  ["rajsferšlus", "молния"],
  ["pertla", "шнурок"],
  ["rukav", "рукав"],
  ["okovratnik", "воротник"],
  ["šav", "шов"],
  ["krpica", "заплатка"],
  ["podstava", "подкладка"],
  ["kopča", "застёжка"],
  ["patent", "кнопка (застёжка)"],
  ["remen", "ремешок (часов)"],
  ["sakо", "пиджак"],
  ["odelo", "костюм"],
  ["smoking", "смокинг"],
  ["trenerka", "спортивный костюм"],
  ["kupaći kostim", "купальник"],
  ["pidžama", "пижама"],
  ["haljinica", "халат"],
];

export const clothingSetInfo = {
  id: "clothing",
  name: "Одежда",
  description: "Предметы одежды и их части",
};
