// Направления и местонахождение
export const directionsWords: [string, string][] = [
  ["napred", "вперёд"],
  ["nazad", "назад"],
  ["gore", "вверх"],
  ["dole", "вниз"],
  ["levo", "налево"],
  ["desno", "направо"],
  ["pravo", "прямо"],
  ["ovde", "здесь"],
  ["tamo", "там"],
  ["blizu", "близко"],
  ["daleko", "далеко"],
  ["severno", "на север"],
  ["južno", "на юг"],
  ["istočno", "на восток"],
  ["zapadno", "на запад"],
  ["sever", "север"],
  ["jug", "юг"],
  ["istok", "восток"],
  ["zapad", "запад"],
  ["preko puta", "напротив"],
  ["pored", "рядом"],
  ["iznad", "над"],
  ["ispod", "под"],
  ["između", "между"],
  ["unutra", "внутри"],
  ["spolja", "снаружи"],
  ["kroz", "через"],
  ["preko", "через/над"],
  ["oko", "вокруг"],
  ["iza", "за/позади"],
  ["ispred", "перед"],
  ["na", "на"],
  ["u", "в"],
  ["sa", "с/со"],
  ["prema", "к/по направлению"],
  ["od", "от"],
  ["do", "до"],
  ["preko ulice", "через дорогу"],
  ["preko mosta", "через мост"],
  ["niz ulicu", "вниз по улице"],
  ["uz ulicu", "вверх по улице"],
  ["iza ugla", "за углом"],
  ["na uglu", "на углу"],
  ["na kraju ulice", "в конце улицы"],
  ["na početku", "в начале"],
  ["u sredini", "в середине"],
  ["u centru", "в центре"],
  ["na periferiji", "на окраине"],
  ["prvi sprat", "первый этаж"],
  ["prizemlje", "нулевой этаж"],
  ["podrum", "подвал"],
  ["tavan", "чердак"],
  ["balkon", "балкон"],
  ["terasa", "терраса"],
  ["dvorište", "двор"],
  ["ulaz", "вход"],
  ["izlaz", "выход"],
  ["stepenice", "лестница"],
  ["lift", "лифт"],
  ["hodnik", "коридор"],
  ["soba", "комната"],
  ["kupatilo", "ванная"],
  ["kuhinja", "кухня"],
  ["dnevna soba", "гостиная"],
  ["spavaća soba", "спальня"],
];

export const directionsSetInfo = {
  id: "directions",
  name: "Направления и местонахождение",
  description: "Направления, стороны света и местоположение",
};
