// Продукты питания
export const foodWords: [string, string][] = [
  ["hleb", "хлеб"],
  ["kifla", "булочка"],
  ["pecivo", "выпечка"],
  ["torta", "торт"],
  ["kolač", "пирожное"],
  ["keks", "печенье"],
  ["palačinka", "блин"],
  ["pita", "пирог"],
  ["burek", "бурек"],
  ["meso", "мясо"],
  ["piletina", "курица"],
  ["svinjetina", "свинина"],
  ["govedina", "говядина"],
  ["jagnjetina", "ягнятина"],
  ["riba", "рыба"],
  ["školjka", "ракушка"],
  ["lignja", "кальмар"],
  ["mleko", "молоко"],
  ["jogurt", "йогурт"],
  ["sir", "сыр"],
  ["kajmak", "каймак"],
  ["pavlaka", "сметана"],
  ["maslac", "масло сливочное"],
  ["jaje", "яйцо"],
  ["povrće", "овощи"],
  ["voće", "фрукты"],
  ["jabuka", "яблоко"],
  ["kruška", "груша"],
  ["pomorandža", "апельсин"],
  ["banana", "банан"],
  ["grožđe", "виноград"],
  ["jagoda", "клубника"],
  ["malina", "малина"],
  ["borovnica", "черника"],
  ["višnja", "вишня"],
  ["šljiva", "слива"],
  ["breskva", "персик"],
  ["kajsija", "абрикос"],
  ["lubenica", "арбуз"],
  ["dinja", "дыня"],
  ["limun", "лимон"],
  ["paradajz", "помидор"],
  ["krastavac", "огурец"],
  ["paprika", "перец"],
  ["luk", "лук"],
  ["beli luk", "чеснок"],
  ["kupus", "капуста"],
  ["šargarepa", "морковь"],
  ["krompir", "картофель"],
  ["pirinač", "рис"],
  ["testenina", "макароны"],
  ["supa", "суп"],
  ["čorba", "похлёбка"],
  ["salata", "салат"],
  ["šećer", "сахар"],
  ["so", "соль"],
  ["biber", "перец (специя)"],
  ["začin", "специя"],
  ["ulje", "масло растительное"],
  ["sirće", "уксус"],
  ["senf", "горчица"],
  ["kečap", "кетчуп"],
  ["majonez", "майонез"],
  ["džem", "варенье"],
  ["med", "мёд"],
  ["čokolada", "шоколад"],
  ["bombon", "конфета"],
  ["sladoled", "мороженое"],
];

export const foodSetInfo = {
  id: "food",
  name: "Продукты",
  description: "Продукты питания",
};
