// Предметы повседневной жизни
export const itemsWords: [string, string][] = [
  ["čaša", "стакан"],
  ["šolja", "кружка"],
  ["tanjir", "тарелка"],
  ["činija", "миска"],
  ["kašika", "ложка"],
  ["viljuška", "вилка"],
  ["nož", "нож"],
  ["knjiga", "книга"],
  ["sveska", "тетрадь"],
  ["papir", "бумага"],
  ["olovka", "ручка"],
  ["hemijska", "шариковая ручка"],
  ["marker", "маркер"],
  ["lenjir", "линейка"],
  ["makaze", "ножницы"],
  ["lepak", "клей"],
  ["selotejp", "скотч"],
  ["spajalica", "скрепка"],
  ["heftalica", "степлер"],
  ["igla", "иголка"],
  ["konac", "нитка"],
  ["dugme", "пуговица"],
  ["lampa", "лампа"],
  ["sijalica", "лампочка"],
  ["prekidač", "выключатель"],
  ["utičnica", "розетка"],
  ["kabl", "кабель"],
  ["ključ", "ключ"],
  ["brava", "замок"],
  ["vrata", "дверь"],
  ["prozor", "окно"],
  ["zavesa", "штора"],
  ["sto", "стол"],
  ["stolica", "стул"],
  ["fotelja", "кресло"],
  ["krevet", "кровать"],
  ["jastuk", "подушка"],
  ["jorgan", "одеяло"],
  ["čaršaf", "простыня"],
  ["peškir", "полотенце"],
  ["ogledalo", "зеркало"],
  ["četka", "щётка"],
  ["češalj", "расчёска"],
  ["sapun", "мыло"],
  ["šampon", "шампунь"],
  ["pasta za zube", "зубная паста"],
  ["četkica za zube", "зубная щётка"],
  ["sat", "часы"],
  ["kalendar", "календарь"],
  ["telefon", "телефон"],
];

export const itemsSetInfo = {
  id: "items",
  name: "Предметы",
  description: "Предметы повседневной жизни",
};
