// Отношения между людьми
export const relationshipsWords: [string, string][] = [
  ["vređa", "обижает"],
  ["povređuje", "ранит/а"],
  ["tuži se", "жалуется"],
  ["žali se", "сокрушается"],
  ["raduje se", "радуется"],
  ["smeje se", "смеётся"],
  ["plače", "плачет"],
  ["ljubi", "целует"],
  ["grli", "обнимает"],
  ["mazi", "ласкает"],
  ["teši", "утешает"],
  ["sastanak", "встреча (по договорённости)"],
  ["izlazak", "встреча (свидание)"],
  ["srete se", "встречается (случайно)"],
  ["sastaje se", "встречается (по договорённости)"],
  ["zabavlja se", "встречается (романтически)"],
  ["izlazi", "встречается/ходит (на свидания)"],
  ["dogovara se", "договаривается"],
  ["obećava", "обещает"],
  ["laže", "лжёт"],
  ["vara", "изменяет"],
  ["prašta", "прощает"],
  ["svađa se", "ссорится"],
  ["prepira se", "препирается"],
  ["raspravlja se", "спорит"],
  ["miri se", "мирится"],
  ["veruje", "верит"],
  ["poverenje", "доверие"],
  ["poštuje", "уважает"],
  ["prezire", "презирает"],
  ["zavidi", "завидует"],
  ["ljubomoran/rna", "ревнует/ревнивый/ая"],
  ["podržava", "поддерживает"],
  ["pomaže", "помогает"],
  ["brine se", "заботится"],
  ["interesuje se", "интересуется"],
  ["obraća pažnju", "обращает внимание"],
  ["ignoriše", "игнорирует"],
  ["odbija", "отвергает"],
  ["prihvata", "принимает"],
  ["razume", "понимает"],
  ["saosećanje", "сочувствие"],
  ["saoseća", "сочувствует"],
  ["druži se", "дружит"],
  ["prijateljstvo", "дружба"],
  ["ljubav", "любовь"],
  ["mržnja", "ненависть"],
  ["strast", "страсть"],
  ["emocija", "эмоция"],
  ["osećaj", "чувство"],
  ["oseća", "чувствует"],
];

export const relationshipsSetInfo = {
  id: "relationships",
  name: "Отношения",
  description: "Взаимоотношения между людьми",
};
