// Совершенные и несовершенные глаголы
export const verbsAspectsWords: [string, string][] = [
  ["radi / uradi", "делает / сделает"],
  ["piše / napiše", "пишет / напишет"],
  ["čita / pročita", "читает / прочитает"],
  ["govori / kaže", "говорит / скажет"],
  ["gleda / pogleda", "смотрит / посмотрит"],
  ["sluša / čuje", "слушает / услышит"],
  ["vidi / ugleda", "видит / увидит"],
  ["razume / shvati", "понимает / поймёт"],
  ["uči / nauči", "учит / выучит"],
  ["ide / ode", "идёт / уйдёт"],
  ["dolazi / dođe", "приходит / придёт"],
  ["odlazi / ode", "уходит / уйдёт"],
  ["ulazi / uđe", "входит / войдёт"],
  ["izlazi / izađe", "выходит / выйдет"],
  ["prolazi / prođe", "проходит / пройдёт"],
  ["prelazi / pređe", "переходит / перейдёт"],
  ["nosi / odnese", "несёт / отнесёт"],
  ["donosi / donese", "приносит / принесёт"],
  ["stavlja / stavi", "ставит / поставит"],
  ["uzima / uzme", "берёт / возьмёт"],
  ["daje / da", "даёт / даст"],
  ["prima / primi", "получает / получит"],
  ["kupuje / kupi", "покупает / купит"],
  ["prodaje / proda", "продаёт / продаст"],
  ["plaća / plati", "платит / заплатит"],
  ["pravi / napravi", "делает / сделает"],
  ["popravlja / popravi", "чинит / починит"],
  ["otvara / otvori", "открывает / откроет"],
  ["zatvara / zatvori", "закрывает / закроет"],
  ["počinje / počne", "начинает / начнёт"],
  ["završava / završi", "заканчивает / закончит"],
  ["nastavlja / nastavi", "продолжает / продолжит"],
  ["prekida / prekine", "прерывает / прервёт"],
  ["jede / pojede", "ест / съест"],
  ["pije / popije", "пьёт / выпьет"],
  ["kuva / skuva", "готовит / приготовит"],
  ["peče / ispeče", "печёт / испечёт"],
  ["meša / promeša", "мешает / смешает"],
  ["seče / iseče", "режет / разрежет"],
  ["pere / opere", "моет / помоет"],
  ["briše / obriše", "вытирает / вытрет"],
  ["čisti / očisti", "чистит / почистит"],
  ["oblači se / obukne se", "одевается / оденется"],
  ["svlači se / svuče se", "раздевается / разденется"],
  ["obuvа se / obuje se", "обувается / обуется"],
  ["poziva / pozove", "звонит / позвонит"],
  ["zove / nazove", "зовёт / назовёт"],
  ["šalje / pošalje", "отправляет / отправит"],
  ["prima / primi", "принимает / примет"],
  ["traži / pronađe", "ищет / найдёт"],
  ["gubi / izgubi", "теряет / потеряет"],
];

export const verbsAspectsSetInfo = {
  id: "verbs-aspects",
  name: "Глагольные виды",
  description: "Совершенные и несовершенные глаголы",
};
