// Набор глаголов
export const verbWords: [string, string][] = [
  ["biti", "быть"],
  ["imati", "иметь"],
  ["hteti", "хотеть"],
  ["moći", "мочь"],
  ["trebati", "нужно"],
  ["znati", "знать"],
  ["videti", "видеть"],
  ["čuti", "слышать"],
  ["govoriti", "говорить"],
  ["pričati", "разговаривать"],
  ["reći", "сказать"],
  ["pitati", "спрашивать"],
  ["odgovoriti", "отвечать"],
  ["razumeti", "понимать"],
  ["misliti", "думать"],
  ["raditi", "работать"],
  ["ići", "идти"],
  ["doći", "прийти"],
  ["otići", "уйти"],
  ["voziti", "водить"],
  ["trčati", "бежать"],
  ["šetati", "ходить"],
  ["sedeti", "сидеть"],
  ["stajati", "стоять"],
  ["skinuti", "снимать"],
  ["ležati", "лежать"],
  ["spavati", "спать"],
  ["jesti", "есть"],
  ["piti", "пить"],
  ["kuvati", "готовить"],
  ["kupiti", "купить"],
  ["prodati", "продать"],
  ["platiti", "платить"],
  ["dati", "дать"],
  ["uzeti", "взять"],
  ["doneti", "принести"],
  ["nositi", "нести"],
  ["čekati", "ждать"],
  ["tražiti", "искать"],
  ["naći", "найти"],
  ["izgubiti", "потерять"],
  ["oblačiti", "одевать"],
  ["otvoriti", "открыть"],
  ["zatvoriti", "закрыть"],
  ["početi", "начать"],
  ["završiti", "закончить"],
  ["voleti", "любить"],
  ["živeti", "жить"],
];

export const verbsSetInfo = {
  id: "verbs",
  name: "Глаголы",
  description: "Основные глаголы сербского языка",
};
