// Совершенный вид глаголов (прошедшее время, м.р.)
export const verbsPerfectiveWords: [string, string][] = [
  ["uradio je", "сделал"],
  ["napisao je", "написал"],
  ["pročitao je", "прочитал"],
  ["rekao je", "сказал"],
  ["pogledao je", "посмотрел"],
  ["čuo je", "услышал"],
  ["ugledao je", "увидел"],
  ["shvatio je", "понял"],
  ["naučio je", "выучил"],
  ["otišao je", "ушёл"],
  ["došao je", "пришёл"],
  ["otišao je", "ушёл"],
  ["ušao je", "вошёл"],
  ["izašao je", "вышел"],
  ["prošao je", "прошёл"],
  ["prešao je", "перешёл"],
  ["odneo je", "отнёс"],
  ["doneo je", "принёс"],
  ["stavio je", "поставил"],
  ["uzeo je", "взял"],
  ["dao je", "дал"],
  ["primio je", "получил"],
  ["kupio je", "купил"],
  ["prodao je", "продал"],
  ["platio je", "заплатил"],
  ["napravio je", "сделал"],
  ["popravio je", "починил"],
  ["otvorio je", "открыл"],
  ["zatvorio je", "закрыл"],
  ["počeo je", "начал"],
  ["završio je", "закончил"],
  ["nastavio je", "продолжил"],
  ["prekinuo je", "прервал"],
  ["pojeo je", "съел"],
  ["popio je", "выпил"],
  ["skuvao je", "приготовил"],
  ["ispekao je", "испёк"],
  ["promešao je", "смешал"],
  ["isekao je", "разрезал"],
  ["oprao je", "помыл"],
  ["obrisao je", "вытер"],
  ["očistio je", "почистил"],
  ["obukao se je", "оделся"],
  ["svukao se je", "разделся"],
  ["obuo se je", "обулся"],
  ["pozvao je", "позвонил"],
  ["nazvao je", "назвал"],
  ["poslao je", "отправил"],
  ["pronašao je", "нашёл"],
  ["izgubio je", "потерял"],
];

export const verbsPerfectiveSetInfo = {
  id: "verbs-perfective",
  name: "Глаголы совершенного вида",
  description: "Завершённые действия в прошедшем времени (м.р.)",
};
